import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import MovieList from "./../src/components/MovieList";

export default function Search() {
  const [searchText, setSearchText] = useState("");
  const [movieList, setMovieList] = useState([]);

  const handlerSearch = async () => {
    if (searchText !== "") {
      const result = await fetch(
        `http://localhost:3000/api/search?q=${searchText}`
      );
      const json = await result.json();
      setMovieList(json.list);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Busca</h1>
        <input
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
        />
        Termo da busca: <h4>{searchText}</h4>
        <button onClick={handlerSearch}>Buscar</button>
        <hr />
        {movieList.length > 0 ? <MovieList movies={movieList} /> : null}
      </main>
    </div>
  );
}
