import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em destaque
        </h1>

        <Link href="/busca">
          <h3 className={styles.buscaLabel}>Ir para a Busca</h3>
        </Link>

        <ul>
          {list.map((item) => (
            <li key={item.id}>
              <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150"></img> <br />
                <span>{item.title}</span>
              </a>
            </li>
          ))}
        </ul>

      </main>
    </div>
  )
}

export async function getServerSideProps() {

  const res = await fetch('http://localhost:3000/api/trending');
  const { list } = await res.json();

  return {
    props: {
      list
    }
  }

}